//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentityWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackendNavigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackendNavigation()
        {
            this.BackendMenu = new HashSet<BackendMenu>();
        }
    
        public byte NavigationId { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string ActiveController { get; set; }
        public string ActiveAction { get; set; }
        public string ActiveCssClass { get; set; }
        public byte Sort { get; set; }
        public bool IsVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackendMenu> BackendMenu { get; set; }
    }
}
